#!/bin/bash
set -e

##################################################################################
#                                                                                #
#                  Modelo De Projeto 'Instalador-Principal'                      #
#                                                                                #
#   Copyright (C) 2021, Ask Config, <https://discord.gg/CSeweRNj3q>              #
#                                                                                #
##################################################################################



output(){
echo -e '\e[36m'$1'\e[0m';
}
        
warn(){
echo -e '\e[31m'$1'\e[0m';
}
        
PANEL=v0.0.1
        
 preflight(){
output "Script V-0.0.1"
output "Copyright © 2021."
}
        
install_options(){
output "Selecionar Injection"
output "[1] Install MisClick ${PANEL}."
read choice
case $choice in
1 ) installoption=1
output "You have selected ${PANEL} panel installation only."
;;
* ) output "Selecione Uma Das Opções Corretas."
install_options
esac
}
sftp() {
echo "* TESTE DE MISCLICK /// Versão Pterodatcyl Encontrada 0.7 | Modulo: Server Reinstaler, SubDomain Maneger File"
}


#Execution
install_options
case $installoption in 
1)   sftp
;;
esac
